#export var := yixi-sha #temporary ev
new := yixi-sha
#test : new := yixi
%t : new := yixi
test : yixi
	#@echo "var => $(var)"
	#@echo "use another file"
	#$(MAKE) -f makefile new:=$(new)
	@echo "new => $(new)"


yixi :
	@echo "new => $(new)"